# Generated by Django 5.2.6 on 2025-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('PPT', 'PPT')], max_length=15)),
                ('document_number', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=20)),
                ('visitor_type', models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('VISITANTE', 'Visitante')], max_length=15)),
                ('always_allowed', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'document_number'), name='unique_document')],
            },
        ),
    ]
